### ISSUE TITLE
关于Fourcastnet的Fourcastnet_model_for_copy/requirements_cpu.txt文件的touch库的问题

### ISSUE THREAD

**Issue by aiwuyouxi** [yungyun0721/AI_global_forecast_model_for_education#1]
# 关于Fourcastnet的Fourcastnet_model_for_copy/requirements_cpu.txt文件的touch库的问题
作者您好，在Fourcastnet的Fourcastnet_model_for_copy/requirements_cpu.txt文件显示需要python的touch库，但是我在安装touch库的时候遇到问题（不仅装不上，而且已经很久没有更新了），我又仔细检查了Fourcastnet_model_for_copy/inference.py文件，发现import torch，是否是requirements_cpu.txt写错了？
![image](https://github.com/user-attachments/assets/ca0e9ae7-9c80-4440-88be-02d913f57d92)

**Comment by yungyun0721** [comment]
應該是寫錯了
感謝你的幫忙
已修改完成
